version: 0.2
env:
  parameter-store:
    BUILD_UPSTREAM_AMI: /CodeBuild/GoldenAMI-Dev
phases:
  pre_build:
    commands:
      - cd 'ami-build'
      - echo "Installing Packer"
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.4.0/packer_1.4.0_linux_amd64.zip && unzip packer.zip
      - echo "Validating Packer template"
      - ./packer validate packer_app.json
  build:
    commands:
      - ./packer build -color=false packer_app.json | tee build.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id.txt || exit 1
      - aws ssm put-parameter --type 'String' --name "/CodeBuild/AMI-DEV-$BUILD_APP_NAME" --value $(head -n 1 ami_id.txt) --overwrite
      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id.txt)/g" ami_builder_event.json
      - aws events put-events --entries file://ami_builder_event.json
      - echo "build completed on `date`"
artifacts:
  files:
    - '**/*'